name: check

on:
  push:
    branches: [main, staging]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - aarch64-darwin
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm')
      || (matrix.system == 'aarch64-darwin' && 'macos-latest') }}

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: setup nix
        uses: ./.github/actions/setup-nix
        with:
          system: ${{ matrix.system }}
      - run: nix profile add .#attic-client
      - uses: ryanccn/attic-action@dc99f5eb1d5c0495aa26f7b56337b30011fa153e # v0.5.2
        with:
          endpoint: https://attic.defelo.de/
          cache: nixpkgs-review-gha
          # atticd-atticadm make-token --sub github --validity 1y --pull nixpkgs-review-gha --push nixpkgs-review-gha
          token: ${{ secrets.NRGHA_ATTIC_TOKEN }}
      - run: nix flake check -L --keep-going
